### ISSUE TITLE
scam and backdoored

### ISSUE THREAD

**Issue by Fullzy90** [Tux-MacG1v/Nosleep-reverseip#3]
Wrong repo sorry lol

**Comment by batmanuwu** [comment]
Which module?

**Comment by cgipascal** [comment]
ofc backdoored its .exe

**Comment by batmanuwu** [comment]
> 

You have any proof? show here.

**Comment by batmanuwu** [comment]
> Wrong repo sorry lol

Maybe **  *_* **

**Comment by batmanuwu** [comment]
> ofc backdoored its .exe

All are **reporting false positives**. It is compile by  [Nukita](https://nuitka.net/pages/overview.html)
Please check this issue: https://github.com/Nuitka/Nuitka/issues/1470
Thanks All.
